- hosts: apps_local
  become: True
  gather_facts: True
  roles:
    - role: playbooks/roles/apps/app

- hosts: datas_local
  become: True
  gather_facts: True
  roles:
    - role: playbooks/roles/apps/data

- hosts: prometheuses_local
  become: True
  gather_facts: True
  roles:
    - role: playbooks/roles/apps/monitoring

- hosts: logging_local
  become: True
  gather_facts: True
  roles:
    - role: playbooks/roles/apps/logging