version: '3.4'

services:
  node_export:
    image: prom/node-exporter:v0.15.1
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  cAdvisor:
    image: google/cadvisor:v0.24.1
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus:v2.0.0
    deploy:
      placement:
        constraints:
          - node.labels.env == jenkins-master
    ports:
      - "9090:9090"
    volumes:
      - /conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/vagrant/prometheus:/promethe

#Run as a service
# docker network create --driver overlay proxy

# docker service create \
# --name node-exporter \
# --mode global \
# --network proxy \
# --mount "type=bind,source=/proc,target=/host/proc" \
# --mount "type=bind,source=/sys,target=/host/sys" \
# --mount "type=bind,source=/,target=/rootfs" \
# prom/node-exporter:0.12.0 \
# -collector.procfs /host/proc \
# -collector.sysfs /host/sys \
# -collector.filesystem.ignored-mount-points \
# "^/(sys|proc|dev|host|etc)($|/)"

# docker service create --name cadvisor \
# --mode global \
# --network proxy \
# --mount "type=bind,source=/,target=/rootfs" \
# --mount "type=bind,source=/var/run,target=/var/run" \
# --mount "type=bind,source=/sys,target=/sys" \
# --mount "type=bind,source=/var/lib/docker,target=/var/lib/docker" \ google/cadvisor:v0.24.1

# docker service create --name prometheus \
# --network proxy \
# -p 9090:9090 \
# --constraint " node.labels.env == jenkins-master " \
# --mount "type=bind,source=/conf/prometheus.yml,target=/etc/prometheus/prometheus.yml" \
# --mount "type=bind,source=/home/vagrant/prometheus,target=/prometheus" prom/prometheus:v1.2.1
